version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:20.0.1

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}

      - run: git checkout . && git clean -df
      - run: cat /dev/null | sbt cachedCiTest
      - run: |
          rm -fv ~/.ivy2/.sbt.ivy.lock
          find ~/.ivy2/cache -name "ivydata-*.properties" -print -delete || echo "empty ivy cache"
          find ~/.sbt        -name "*.lock"               -print -delete
          rm -rf ./.git
          rm -rf ./project/target #clean doesn't clean meta-build

      - save_cache:
          paths:
            - ~/.ivy2/cache
            - ~/.sbt
            - ~/.cache/coursier
            - ./
          key: v1-dependencies-{{ .Branch }}-{{ epoch }}
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
