name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Cache SBT ivy cache
        uses: actions/cache@v3
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-ivy-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-ivy-

      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-sbt-

      - name: Cache coursier cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-coursier-

      - name: Cache project
        uses: actions/cache@v3
        with:
          path: ./
          key: ${{ runner.os }}-project-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-project-

      - name: Checkout current
        run: git checkout . && git clean -df
      - name: Run tests
        run: sbt cachedCiTest
      - name: Clean caches
        run: |
          rm -fv ~/.ivy2/.sbt.ivy.lock
          find ~/.ivy2/cache -name "ivydata-*.properties" -print -delete || echo "empty ivy cache"
          find ~/.sbt        -name "*.lock"               -print -delete
          rm -rf ./.git
          rm -rf ./project/target #clean doesn't clean meta-build

